### PR TITLE
Vue port

### PR DESCRIPTION
**Pull request by adamwight**
@Amamgbu nothing ready to merge yet, but I've been slowly piecing together a literal translation of containers into Vue components.  I'll un-WIP at the next checkpoint, once I can get equivalent functionality as the current `main` branch.

I haven't started any of the fun (unsarcastically!) wiring, replacing jQuery direct DOM manipulation and event handling with Vue reactive data.

Local development proxying should work now, if you want to try this branch and let me know the outcome?  It's still not quite the way we should do full "production"-quality routing, I haven't figured out what that should look like but assuming it's something like Nginx or Apache config as the reverse proxy, routing requests to the proper backend server in pretty much the same fashion but at the network layer rather than in one of the applications.  Maybe it doesn't matter at our volume.

### CODE REVIEW

**Review by adamwight — COMMENTED** [review]
I discovered that the Vue single-file component parser is stricter and catches some errors in the HTML.

**Comment by Amamgbu** [comment]
Hi Adam,
Thanks a lot for this. Currently going through the code.

**Comment by adamwight** [comment]
I think this is finally equivalent to the `main` branch again, at least I can submit queries and I see the result tables.

We still aren't taking advantage of Vue, but all the pieces are in place to incrementally shift paradigms.

Feel free to merge if it works for you locally!

**Comment by adamwight** [comment]
Deprecated by #6

**Pull request closed without merging**
